### ISSUE TITLE
Move token manager to fabric8-common

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-cluster#6]
We need to update https://github.com/fabric8-services/fabric8-common/tree/master/token package and reuse it in fabric8-cluster.

The current token package in fabric8-cluster is in better state for common. So we should base token package in common on https://github.com/fabric8-services/fabric8-cluster/tree/master/token

Plus add DefaultManager() function from https://github.com/fabric8-services/fabric8-auth/blob/master/token/token.go#L62 too.

**Comment by xcoulon** [comment]
I can work on it
