### ISSUE TITLE
Obtain Cluster Service Account token

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-cluster#8]
1. Introduce SA token obtaining code to fabric8-common. Something like:
`token, error = token.ServiceAccountToken(ctx context.Context, configuration.Configuration, saName, saSecret string) (token string, err error)`

where
```
type Configuration interface {
    AuthServiceURL() string
}
```

Then we can use it in cluster service and other places.

Depends on https://github.com/fabric8-services/fabric8-cluster/issues/6 & #12

**Comment by dipak-pawar** [comment]
I will start with this once @xcoulon finished #6

**Comment by xcoulon** [comment]
the `ServiceAccountToken`  function already exists in fabric8-common since fabric8-services/fabric8-common#56: https://github.com/fabric8-services/fabric8-common/blob/master/auth/token.go#L319

**Comment by xcoulon** [comment]
@alexeykazakov we have all the code needed in [fabric8-services/fabric8-common](https://github.com/fabric8-services/fabric8-common/blob/master/auth/token.go#L319) to obtain a service account token,  but do we need one in `cluster` service?

**Comment by alexeykazakov** [comment]
No. We can close this one.
