### ISSUE TITLE
Reuse pkgs from `fabric8-common`

### ISSUE THREAD

**Issue by xcoulon** [fabric8-services/fabric8-cluster#9]
Let's try to avoid code duplication and reuse the pkgs from https://github.com/fabric8-services/fabric8-common when it's doable.

- [x] goamiddleware
- [ ] jsonapi
- [ ] rest
- [x] sentry - https://github.com/fabric8-services/fabric8-cluster/pull/10

**Comment by xcoulon** [comment]
> cc: @dipak-pawar
> 
> BTW I was thinking of renaming "rest" package to "http" when moving to common.

Hehe, @alexeykazakov I'm doing that exact renaming as part of https://github.com/fabric8-services/fabric8-common/issues/18 which I'm currently working on! 😃

**Comment by xcoulon** [comment]
> > cc: @dipak-pawar
> > BTW I was thinking of renaming "rest" package to "http" when moving to common.
> 
> Hehe, @alexeykazakov I'm doing that exact renaming as part of [fabric8-services/fabric8-common#18](https://github.com/fabric8-services/fabric8-common/issues/18) which I'm currently working on! 😃

Actually, there's already an `httpsupport` pkg (https://github.com/fabric8-services/fabric8-common/tree/master/httpsupport) so I suggest I move the content of `rest` in there, instead.

**Comment by alexeykazakov** [comment]
I would still rename httpsupport to http. To many *support packages :) Hopping it's not wildly used yet. WDYT?
